// <auto-generated />
namespace Controle.Migrations.ContextoDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InclusãoDasTabelas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InclusãoDasTabelas));
        
        string IMigrationMetadata.Id
        {
            get { return "201801161650057_InclusãoDasTabelas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
